### PR TITLE
Mariam installed vite

### PR DESCRIPTION
**Pull request by MoyosoreCoder**

### CODE REVIEW

**Comment by gabrie-lhilarion** [comment]
Ok let me take a look

**Review by gabrie-lhilarion — APPROVED** [review]
Looks good, you can merge now.

**Comment by MoyosoreCoder** [comment]
nice

**Comment by MoyosoreCoder** [comment]
nice work

**Review by MoyosoreCoder — COMMENTED** [review]
nice

**Comment by MoyosoreCoder** [comment]
nice

**Review by MoyosoreCoder — COMMENTED** [review]
nice work

**Comment by MoyosoreCoder** [comment]
Nice work

**Pull request merged**
